### ISSUE TITLE
Finish FreeCodeCamp's "JavaScript Algorithms and Data Structures" courses

### ISSUE THREAD

**Issue by ismailarilik** [softeria-test/grid-view-ts#28]
The link to the courses: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/

## Courses

- [x] Basic JavaScript 
- [x] ES6
- [x] Regular Expressions 
- [x] Debugging
- [x] Basic Data Structures
- [x] Basic Algorithm Scripting
- [x] Object Oriented Programming 
- [x] Functional Programming
- [x] Intermediate Algorithm Scripting
- [x] JavaScript Algorithms and Data Structures Projects

## Sub-To-Dos

- [x] Please claim and attach your certification here after you finished courses.

**Comment by emreliman** [comment]
https://www.freecodecamp.org/certification/fcc54dba028-7451-43d4-a6b1-c9bd8d3d0db1/javascript-algorithms-and-data-structures
