### ISSUE TITLE
Experience what is the best way to test a component

### ISSUE THREAD

**Issue by ismailarilik** [softeria-test/grid-view-ts#39]
Try those:

- [x] Test component with vue-test-utils
- [x] Extract logic in the component to TS files and test those files

And look at these metrics:

- [x] Which one is easier?
- [x] Which one provides more isolation? 
- [x] Which one provides more coverage?

**Comment by emreliman** [comment]
Testing functions is easier. I got the same result for coverage and isolation, but moving the scripts out provides more readability.
